title: Hans5958's Redirection Service
description: This is a redirect website.
baseurl: "/jekyll"
url: "/"
destination: public
markdown: kramdown
exclude: ["README.md"]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "redirect"